FROM openjdk:17-jdk

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o JAR da aplicação para o contêiner
COPY out/artifacts/MSlogin_jar/MSlogin.jar mslogin.jar

# Porta em que a aplicação expõe
EXPOSE 8082

# Comando para executar a aplicação
CMD ["java", "-jar", "mslogin.jar"]