FROM openjdk:17-jdk

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o JAR da aplicação para o contêiner
COPY out/artifacts/MSAlunos_jar/MSAlunos.jar msalunos.jar

# Porta em que a aplicação expõe
EXPOSE 8080

# Comando para executar a aplicação
CMD ["java", "-jar", "msalunos.jar"]